In [40]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats
%precision 3

'%.3f'

In [5]:
sample_array = np.array([1,2,3,4,5])
sample_array

array([1, 2, 3, 4, 5])

In [6]:
sample_array * 2

array([ 2,  4,  6,  8, 10])

In [7]:
sample_array.shape

(5,)

In [9]:
sample_df = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array * 2,
    'col3' : ["a", "b", "c", "d", "e"]
})
print(sample_df)

   col1  col2 col3
0     1     2    a
1     2     4    b
2     3     6    c
3     4     8    d
4     5    10    e


In [20]:
%precision 3

'%.3f'

In [21]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [24]:
sp.sum(fish_data)

40

In [25]:
len(fish_data)

10

In [26]:
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.000

In [27]:
sp.mean(fish_data)

4.000

In [31]:
sigma_2_sample = sp.sum((fish_data - mu)**2) / N
sigma_2_sample

1.200

In [34]:
sigma_2 = sp.sum((fish_data - mu) **2) / (N - 1)
sigma_2

1.333

In [35]:
sp.var(fish_data, ddof = 1)

1.333

In [36]:
sp.var(fish_data, ddof = 0)

1.200

In [37]:
sigma = sp.sqrt(sigma_2)
sigma

1.155

In [38]:
sp.std(fish_data, ddof = 1)

1.155

In [39]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [41]:
fish_data / sigma

array([ 1.732,  2.598,  2.598,  3.464,  3.464,  3.464,  3.464,  4.33 ,
        4.33 ,  5.196])

In [42]:
sp.std(fish_data / sigma, ddof = 1)

1.000

In [43]:
standard = (fish_data - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [44]:
sp.mean(standard)

0.000

In [45]:
sp.std(standard, ddof = 1)

1.000

In [46]:
sp.amax(fish_data)

6

In [47]:
sp.amin(fish_data)

2

In [48]:
sp.median(fish_data)

4.000

In [49]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [50]:
#平均値
sp.mean(fish_data_2)

13.400

In [51]:
#中央値
sp.median(fish_data_2)

4.000

In [54]:
#statsを用いて四分位点を求める
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)

3.000

In [55]:
stats.scoreatpercentile(fish_data_3, 75)

7.000

In [1]:
pwd

'/Users/yorimoto/PyStat'

In [48]:
fish_multi = pd.read_csv('../statistics_python/3-2-1-fish_multi.csv')
print(fish_multi)
print("==========")

#種類ごと
group = fish_multi.groupby("species")
print(group.mean())
print("==========")

#標準偏差も
print(group.std(ddof=1))
print("==========")

#平均値や四部位点などまとめて
group.describe()

  species  length
0       A       2
1       A       3
2       A       4
3       B       6
4       B       8
5       B      10
         length
species        
A             3
B             8
         length
species        
A           1.0
B           2.0


length                                    
         count mean  std  min  25%  50%  75%   max
species                                           
A          3.0  3.0  1.0  2.0  2.5  3.0  3.5   4.0
B          3.0  8.0  2.0  6.0  7.0  8.0  9.0  10.0

In [35]:
shoes = pd.read_csv("../statistics_python/3-2-2-shoes.csv")
print('=== データ構成 ===')
print(shoes)

# 引数：　データ、集計対象、関数、行、列
cross = pd.pivot_table(
    data = shoes,
    values = "sales",
    aggfunc = "sum",
    index = "store",
    columns = "color"
)
print("=== pandas.pivot_tableの使用例 ===")
print(cross)

=== データ構成 ===
   store color  sales
0  tokyo  blue     10
1  tokyo   red     15
2  osaka  blue     13
3  osaka   red      9
=== pandas.pivot_tableの使用例 ===
color  blue  red
store           
osaka    13    9
tokyo    10   15


In [36]:
cov_data = pd.read_csv("../statistics_python/3-2-3-cov.csv")
print("=== データ構成 ===")
print(cov_data)

=== データ構成 ===
      x   y
0  18.5  34
1  18.7  39
2  19.1  41
3  19.7  38
4  21.5  45
5  21.7  41
6  21.8  52
7  22.0  44
8  23.4  44
9  23.8  49


In [44]:
# データの取り出し
x = cov_data["x"]
y = cov_data["y"]
N = len(cov_data)

# 平均値の計算
mu_x = np.mean(x)
mu_y = np.mean(y)

In [41]:
# 共分散
sum((x - mu_x) * (y - mu_y)) / N

# 共分散 (N - 1)
sum((x - mu_x) * (y - mu_y)) / (N - 1)

6.906
7.67333333333


In [51]:
print("共分散")
print(sp.cov(x, y, ddof=0))

print("共分散（N - 1）")
print(sp.cov(x, y, ddof=1))

共分散
[[  3.282   6.906]
 [  6.906  25.21 ]]
共分散（N - 1）
[[  3.646   7.673]
 [  7.673  28.011]]


In [52]:
# 分散の計算
sigma_2_x = sp.var(x, ddof=1)
sigma_2_y = sp.var(y, ddof=1)
# ddof=1なのは分母と分子で割る数を合わせるため（cov 参照）
# 割る数が同じならNでも(N-1)でもどちらでも良い

# 相関係数
rho = cov / sp.sqrt(sigma_2_x * sigma_2_y)
rho

0.759

In [53]:
 # 相関行列
sp.corrcoef(x, y)

array([[ 1.   ,  0.759],
       [ 0.759,  1.   ]])